email:
  imap:
    host: imap.qq.com
    port: 993
    username: xxx@qq.com
    password: ******
    mailbox: INBOX
  
rawdata_path: rawdata
data_path: data
archive_path: archive

passwords:
  - "123456"
  - "222222"

balance_accounts:
 - "Assets:BoC:Card:XXX"
 - "Assets:CCB:Card:XXX"
 - "Assets:Alipay:YueBao"
 - "Assets:WeChat:Balance"

web:
  host: "0.0.0.0"
  port: 8000
  password: "change_this_password"
  jwt_secret: "change_this_secret_key"
  token_expire_days: 7