services:
  ihopecash:
    build: .
    container_name: ihopecash
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./env.yaml:/app/env.yaml
      - ./data:/app/data
      - ./rawdata:/app/rawdata
      - ./archive:/app/archive
      - ./certs:/app/certs
